name: Build and Deploy React App as Docker Container

on:
  push:
    branches:
      - main
  workflow_dispatch:   # allows manual trigger from GitHub Actions

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Login to Azure using Service Principal
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3. Login to Azure Container Registry
      - name: Docker login to ACR
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login myreactregistryweu.azurecr.io \
            -u "${{ secrets.ACR_USERNAME }}" --password-stdin

      # 4. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t myreactregistryweu.azurecr.io/my-react-frontend:${{ github.sha }} .

      # 5. Push Docker image to ACR
      - name: Push Docker image to ACR
        run: |
          docker push myreactregistryweu.azurecr.io/my-react-frontend:${{ github.sha }}

      # 6. Deploy image to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "my-react-frontend-weu"
          images: "myreactregistryweu.azurecr.io/my-react-frontend:${{ github.sha }}"
